// AUTO-GENERATED by iket-assets/process.py — do not hand-edit.
// Every photo is licence-cleared: CC0 / CC BY-SA / Unsplash. Provenance
// (creator + source URL) is retained so /disclosure can credit them.
import type { ImageMetadata } from 'astro';

import hero_paneer_karahi from '../assets/photos/hero-paneer-karahi.jpg';
import wide_chicken_skewers from '../assets/photos/wide-chicken-skewers.jpg';
import ghee_jar from '../assets/photos/ghee-jar.jpg';
import paneer_tikka_skewers from '../assets/photos/paneer-tikka-skewers.jpg';
import butter_chicken_bowl from '../assets/photos/butter-chicken-bowl.jpg';
import egg_curry_anda from '../assets/photos/egg-curry-anda.jpg';
import lamb_korma_bowl from '../assets/photos/lamb-korma-bowl.jpg';
import mutton_curry_bowl from '../assets/photos/mutton-curry-bowl.jpg';
import okra_masala_bowl from '../assets/photos/okra-masala-bowl.jpg';
import gobi_masala_bowl from '../assets/photos/gobi-masala-bowl.jpg';
import masala_dabba from '../assets/photos/masala-dabba.jpg';
import spice_box_topdown from '../assets/photos/spice-box-topdown.jpg';
import whole_spices_plate from '../assets/photos/whole-spices-plate.jpg';
import chicken_tikka_plate from '../assets/photos/chicken-tikka-plate.jpg';
import kofta_korma_bowl from '../assets/photos/kofta-korma-bowl.jpg';
import og_default from '../assets/photos/og-default.jpg';

export interface Photo {
  slug: string;
  src: ImageMetadata;
  alt: string;
  title: string;
  license: string;
  creator: string;
  sourceUrl: string;
  lqip: string;
}

export const photos = {
  'hero-paneer-karahi': {
    slug: 'hero-paneer-karahi',
    src: hero_paneer_karahi,
    alt: "Paneer simmering in a glossy orange butter-masala gravy in a steel karahi",
    title: "Shahi paneer roll with Makhmali gravy 2",
    license: "by-sa 4.0",
    creator: "Vis M",
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=131420697",
    lqip: "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQAAkAA4BaJbACdAC4JbwxAAD+76hWlwRxaim3vjztlk7Q8Oavkkv6Az/rIzK50VkH/VDj555Cer6HzkMxgy9woAA=",
  },
  'wide-chicken-skewers': {
    slug: 'wide-chicken-skewers',
    src: wide_chicken_skewers,
    alt: "Marinated chicken skewers grilled over an open flame",
    title: "Awadhi seekh kebab",
    license: "by-sa 2.0",
    creator: "reivax",
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=18036655",
    lqip: "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQAAkAA4BaJZACdAEPe1qdeAAA/sB2VnPcQ0OUmg9UommmOijBhuaEz20dize5aRKzNlUUTIFkAAAA",
  },
  'ghee-jar': {
    slug: 'ghee-jar',
    src: ghee_jar,
    alt: "A glass jar of golden ghee against a clean white background",
    title: "File:Butterschmalz-3.jpg",
    license: "by-sa 3.0",
    creator: "Rainer Z ...",
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=5639258",
    lqip: "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQABAAA4BaJbACdAEMgBzrMAD93bC/jdcJFNzn/oR97rBvoFsuy/aZhoOOgCCf4Br8Bt/3JCgWH9sWxV/TJ/MmRnlKQugAAAA=",
  },
  'paneer-tikka-skewers': {
    slug: 'paneer-tikka-skewers',
    src: paneer_tikka_skewers,
    alt: "Grilled paneer tikka skewers with capsicum and onion on a white tray",
    title: "Barbequed Paneer Tikka",
    license: "by-sa 4.0",
    creator: "SuVaM Epicure",
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=101989306",
    lqip: "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoQAAwAA4BaJbACdAELYv4bmTAAAP2qOUwKF6wWoem+9oBNht1OO4SGheqBLFybNNf9rB9t36E/e06HXvDXXKXRL3RkUON/OQwAAA==",
  },
  'butter-chicken-bowl': {
    slug: 'butter-chicken-bowl',
    src: butter_chicken_bowl,
    alt: "Butter chicken in a bowl, finished with cream and fresh coriander",
    title: "2020-02-22 20 57 16 Butter chicken in tomato sauce with fenugreek at Karma Modern Indian in Washingt",
    license: "by-sa 4.0",
    creator: "Famartin",
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=87411938",
    lqip: "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAwAgCdASoQAAwAA4BaJbACdAEfk5y01mfzGAD+C5TGIiVxRZPqFvVPnhGDQo5lCK3lfztOW4IWOOLeIYIlwJUJ/XPtZUssCdqQtyT+zgAAAA==",
  },
  'egg-curry-anda': {
    slug: 'egg-curry-anda',
    src: egg_curry_anda,
    alt: "Halved boiled eggs in a rich tomato and coriander curry",
    title: "File:Egg Curry (Anda Curry).JPG",
    license: "by-sa 4.0",
    creator: "Mdsmds0",
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=40876268",
    lqip: "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAwAA4BaJbACdAD0c54+HAAA/vGnn3UtXzjRfInKZLC0qh8+0T9CsOfoKhJ6s6NMmz3rKEa/eEtjyb78ixGZajjCJeZLssrjL7TeYgrgAA==",
  },
  'lamb-korma-bowl': {
    slug: 'lamb-korma-bowl',
    src: lamb_korma_bowl,
    alt: "Lamb korma in a scalloped porcelain bowl with a golden cashew gravy",
    title: "Mutton Rogan Josh curry",
    license: "by-sa 4.0",
    creator: "Kajori.p",
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=40984113",
    lqip: "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwAgCdASoQAAwAA4BaJbACdADREvvMvkg8wAD+6E8KsMpC6p8f/0dco9XZi6Ab2LvBz5e3wxctj7P0WrrsYurHyW9ZOHIBJK9QLBAAAAA=",
  },
  'mutton-curry-bowl': {
    slug: 'mutton-curry-bowl',
    src: mutton_curry_bowl,
    alt: "Goat curry with whole spices photographed on a dark background",
    title: "Bengali mutton curry - Kolkata - West Bengal",
    license: "by-sa 4.0",
    creator: "Pkd2512",
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=103621063",
    lqip: "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoQAAwAA4BaJZACdAEenBWUrlwA/t47dfnKRlZ3iFgMYdMOyLe/gWOmPotajcCwNB7lltf6ypHZflex+MrpbDwhgcSztVEVFsk4fHZvmxvCl4Q2WYAAAA==",
  },
  'okra-masala-bowl': {
    slug: 'okra-masala-bowl',
    src: okra_masala_bowl,
    alt: "Bhindi masala (okra) in a white bowl on a dark counter",
    title: "Bhindi Fry",
    license: "by-sa 4.0",
    creator: "Shreya Shetty",
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=40661307",
    lqip: "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAABQAgCdASoQAAwAA4BaJagCdAEfbpyOjyRE1AAA/vXwtK23phfy+z49IiJRT9/mT7PjuftMDtyVzTjhFwNe2BDa5H2V/LF0gKcyyKCAAAA=",
  },
  'gobi-masala-bowl': {
    slug: 'gobi-masala-bowl',
    src: gobi_masala_bowl,
    alt: "Gobi masala, spiced cauliflower, in a steel bowl on a dark backdrop",
    title: "File:Cauliflower Potatoes Curry.JPG",
    license: "by-sa 4.0",
    creator: "Mdsmds0",
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=40796111",
    lqip: "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAgCdASoQAAwAA4BaJbACdJIAxwDeWgaiEt023NkAAP4VyyQSqT9pg1hPttGHfsAJCtTC0AE4E/oPNCN1vfnGSsBzjKmp+zRePW35zKiOhox/tOhSeDxAAAA=",
  },
  'masala-dabba': {
    slug: 'masala-dabba',
    src: masala_dabba,
    alt: "A stainless steel masala dabba filled with colourful Indian spices",
    title: "Spice box with various blends",
    license: "by-sa 4.0",
    creator: "Waitinginstars",
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=183358049",
    lqip: "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAwAgCdASoQAAwAA4BaJbACdAD1kkr/vBNP4AD+rW4chLIPgLo8VhJshVAWwb1CQo3k8CcGQYYSgT0eyIoOyqOoe3tyv3Yrv3NEe0tvvVbN4C2ohcAAAA==",
  },
  'spice-box-topdown': {
    slug: 'spice-box-topdown',
    src: spice_box_topdown,
    alt: "Top-down view of a seven-compartment Indian spice box",
    title: "File:Spices in an Indian kitchen.JPG",
    license: "by-sa 3.0",
    creator: "Dharmadhyaksha",
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=24494338",
    lqip: "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoQAAwAA4BaJbACdDiAASRhxfKAAAD+9dlLzdMIsFz42f6cO/TUCzgdHYaGjA+7n8HI5d+AogKRIDsFtbp08ubeBt4/vScHCnx4XNUnpedGAAAA",
  },
  'whole-spices-plate': {
    slug: 'whole-spices-plate',
    src: whole_spices_plate,
    alt: "Whole Indian spices \u2014 bay leaf, cinnamon, cardamom and turmeric \u2014 on a plate",
    title: "Indian spices (garam masala components) (49684334741)",
    license: "by 2.0",
    creator: "spurekar",
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=89967347",
    lqip: "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAwAgCdASoQAAwAA4BaJbACdADRWHMWigLxgAD+xbikr5rLKtS3f7lQ8FzSGTyWSsvyKFqOH4Dgdbv73V959dRTMB5r1J9HR+vHqevCJuTAVdn4/nOBHy9+/uv6xsz7tl2c88gW93xGe6ga5SPgeF4AAAA=",
  },
  'chicken-tikka-plate': {
    slug: 'chicken-tikka-plate',
    src: chicken_tikka_plate,
    alt: "Chicken tikka on a blue plate with onion, lime and mint chutney",
    title: "London - Battersea - Cinnamon kitchen restaurant, Tandoori Chicken Tikka",
    license: "cc0 1.0",
    creator: "Romainbehar",
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=81038864",
    lqip: "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAwAA4BaJQBOgB6S4ZpZTE8AAP71GQSDyDXFE1C6+ivuWMpGulCdxTW/E9PIDOVNXy2M5idmdo9NofndVgiHrUIPGJgAAAA=",
  },
  'kofta-korma-bowl': {
    slug: 'kofta-korma-bowl',
    src: kofta_korma_bowl,
    alt: "Kofta curry in a golden korma sauce, garnished with coriander",
    title: "Vegetarian homemade Kofta with gravy from North India",
    license: "by-sa 4.0",
    creator: "Ravi Dwivedi",
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=116793973",
    lqip: "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoQAAwAA4BaJbACdLoAATBoAADWfkGpT+Q6lUPNQv/i0Otru1baq/bwKRwHgAAA",
  },
  'og-default': {
    slug: 'og-default',
    src: og_default,
    alt: "Keto Indian food: paneer butter masala",
    title: "Shahi paneer roll with Makhmali gravy 2",
    license: "by-sa 4.0",
    creator: "Vis M",
    sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=131420697",
    lqip: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAgAA4BaJbACdADHrB5ljIAA/u0emKk4S83L4zPEnH4eWya+snOHQGAujR4dn57vyo54kcqfhjr4PGOtOu2yfAAAAA==",
  },
} as const satisfies Record<string, Photo>;

export type PhotoSlug = keyof typeof photos;

export function photo(slug: PhotoSlug): Photo { return photos[slug] as Photo; }
